### ISSUE TITLE
The Bubble widget gave me bad performance

### ISSUE THREAD

**Issue by mahmoud-haj-ali** [vi-k/bubble#25]
When i used it in ListView.Builder the frames down to 7 fps.
I tried to change it to Container and the frames up to 40 fps.

**Comment by felipegonzalez1994** [comment]
same problem here, I am making a chat application and use bubble with listview.builder, but the performance is very bad. In the emulator the performance is very nice but when i run the app in a rial device(samsung j7 prime, my minimal device target) the performance is desastrous. Im use devtools to see a performance in device.
This test was performed in a default flutter application with only one Listview.Builder with 20 chatBubbles. 

I suspect the problem comes from drawing the nip, makes an exaggerated use of gpu, the same thing happens with FlutterChatBubble.


I recommend you use flutter devtools to see the performance.

![Screenshot_15](https://user-images.githubusercontent.com/29465943/100769136-68daf800-33da-11eb-9ca4-48187604e0c6.png)

**Comment by mahmoud-haj-ali** [comment]
I replaced the Bubble with Container for now until we get some help here.
The performance is a lot different with Container.

**Comment by ashishbeck** [comment]
The package has been updated but not published to the pub website. You will have to import from the github repo directly to get the optimal performance version
```
bubble:
 git:
  url: git://github.com/vi-k/bubble.git
  ref: master
```

It worked for me

**Comment by vi-k** [comment]
The new version published. Sorry.
